//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDofit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.Factura_Productos = new HashSet<Factura_Productos>();
        }
    
        public int Factura_Id { get; set; }
        public int Numero_Factura { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Trabajador_Id { get; set; }
        public int Proveedor_Id { get; set; }
        public int Tipo_Movimiento_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura_Productos> Factura_Productos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual Tipo_Movimientos Tipo_Movimientos { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
    }
}
