//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDofit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suscripciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suscripciones()
        {
            this.Visitas = new HashSet<Visitas>();
        }
    
        public string Suscripcion_Id { get; set; }
        public int Numero_Suscripcion { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Finalizacion { get; set; }
        public string Costo { get; set; }
        public Nullable<double> Descuento { get; set; }
        public bool Activo { get; set; }
        public int Cliente_Id { get; set; }
        public int Plan_Clientes_Id { get; set; }
        public int Trabajador_Id { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Plan_Clientes Plan_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visitas> Visitas { get; set; }
        public virtual Trabajadores Trabajadores { get; set; }
    }
}
